### ISSUE TITLE
Create GitHub Pages demo

### ISSUE THREAD

**Issue by DanielRuf** [radek-anuszewski/HTML-picture-tag-in-practice#1]
Can you enable GH Pages for the master branch and share the URL in your article?

**Comment by radek-anuszewski** [comment]
Hi @DanielRuf !
Apologies for delay, I have created a GH Page and paste it to article: https://medium.com/front-end-weekly/html-picture-tag-in-practice-png-and-webp-formats-5a3fc51b5998
Hope it's what you mean
